#!/bin/bash

# The target directory
TARGET_DIR=~/web/stageoneeducation

# Check if the current directory is the target directory
if [ "$(pwd)" != "$TARGET_DIR" ]; then
    echo "Error: Not in directory $TARGET_DIR"
    exit 1
fi

cd ai-network
npm run build
cd ..

cd drone-workshop
npm run build
cd ..

cd feedback
npm run build
cd ..

echo "Building site..."
jekyll build --source jekyll --destination www "$@"

echo "Deploying..."

firebase use stageoneed
firebase deploy --only hosting

echo "Deploying feedback application..."
cd feedback
./deploy-feedback.sh
cd ..
