#!/bin/bash

# NOTE NOTE NOTE
# The nginx config for stageoneeducation2.com is set up in the musicgen project
# NOTE NOTE NOTE


# The target directory
TARGET_DIR=~/web/stageoneeducation

# Check if the current directory is the target directory
if [ "$(pwd)" != "$TARGET_DIR" ]; then
    echo "Error: Not in directory $TARGET_DIR"
    exit 1
fi

cd drone-workshop
npm run build
cd ..

echo "Building site..."
jekyll build --source jekyll --destination www "$@"

echo "Deploying..."

# Copy the site to stageoneeducation2.com
rsync -avz --delete www/* stageoneeducation2.com:www/
